cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

junit:
  image: maven:3.6.1-jdk-11
  before_script:
    - . Code/setup-mvn-proxy.sh
  script:
    - cd Code && mvn test --batch-mode
